#!/usr/bin/env python3
"""
Simple 1D CNN for BPSK signal separation from jamming/noise.
Trains on the synthetic data generated by data.py and evaluates SNR improvement.

Usage:
  python train_cnn.py --data artifacts/gnss_synth_sweepcw_20k.npz --epochs 50
"""
import argparse
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
from pathlib import Path


class SignalDataset(Dataset):
    """Dataset wrapper for the NPZ data."""
    def __init__(self, X, Y):
        self.X = torch.from_numpy(X).float()
        self.Y = torch.from_numpy(Y).float()
    
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, idx):
        return self.X[idx], self.Y[idx]


class SignalDenoiser1DCNN(nn.Module):
    """
    Simple 1D CNN for signal separation.
    Input: [batch, 512] (256 samples * 2 for Re/Im flattened)
    Output: [batch, 512] (cleaned signal, same format)
    """
    def __init__(self, input_dim=512, hidden_channels=[64, 128, 256, 128, 64]):
        super().__init__()
        
        # Reshape input to [batch, 2, 256] for conv1d (2 channels: Re, Im)
        layers = []
        in_ch = 2
        
        # Encoder
        for out_ch in hidden_channels[:3]:
            layers.append(nn.Conv1d(in_ch, out_ch, kernel_size=7, padding=3))
            layers.append(nn.BatchNorm1d(out_ch))
            layers.append(nn.ReLU())
            in_ch = out_ch
        
        # Bottleneck
        layers.append(nn.Conv1d(in_ch, hidden_channels[2], kernel_size=5, padding=2))
        layers.append(nn.BatchNorm1d(hidden_channels[2]))
        layers.append(nn.ReLU())
        
        # Decoder
        for out_ch in hidden_channels[3:]:
            layers.append(nn.Conv1d(in_ch, out_ch, kernel_size=7, padding=3))
            layers.append(nn.BatchNorm1d(out_ch))
            layers.append(nn.ReLU())
            in_ch = out_ch
        
        # Output layer (back to 2 channels)
        layers.append(nn.Conv1d(in_ch, 2, kernel_size=7, padding=3))
        
        self.network = nn.Sequential(*layers)
    
    def forward(self, x):
        # x: [batch, 512] -> reshape to [batch, 2, 256]
        batch_size = x.size(0)
        x = x.view(batch_size, 2, -1)
        
        # Apply network
        x = self.network(x)
        
        # Flatten back to [batch, 512]
        x = x.view(batch_size, -1)
        return x


def calculate_snr(signal, noise):
    """
    Calculate SNR in dB.
    signal: clean/target signal
    noise: error/noise (predicted - target)
    """
    signal_power = np.mean(signal ** 2)
    noise_power = np.mean(noise ** 2)
    
    if noise_power < 1e-12:
        return 100.0  # Very high SNR
    
    snr_linear = signal_power / noise_power
    snr_db = 10 * np.log10(snr_linear)
    return snr_db


def calculate_evm(predicted, target):
    """
    Calculate Error Vector Magnitude (EVM) as a percentage.
    
    EVM measures constellation distortion:
    EVM = sqrt(mean(|error|^2) / mean(|ideal|^2)) * 100%
    
    Args:
        predicted: flattened [Re, Im] array
        target: flattened [Re, Im] array (clean reference)
    
    Returns:
        EVM in percentage
    """
    # Convert flattened [Re, Im] back to complex
    pred_cplx = predicted[::2] + 1j * predicted[1::2]
    tgt_cplx = target[::2] + 1j * target[1::2]
    
    # Error vector
    error = pred_cplx - tgt_cplx
    
    # EVM calculation
    error_power = np.mean(np.abs(error) ** 2)
    signal_power = np.mean(np.abs(tgt_cplx) ** 2)
    
    if signal_power < 1e-12:
        return 0.0
    
    evm = np.sqrt(error_power / signal_power) * 100.0
    return evm


def evaluate_snr(model, dataloader, device):
    """Evaluate achieved SNR and EVM on a dataset."""
    model.eval()
    all_targets = []
    all_outputs = []
    all_inputs = []
    
    with torch.no_grad():
        for inputs, targets in dataloader:
            inputs_device = inputs.to(device)
            outputs = model(inputs_device)
            
            all_inputs.append(inputs.cpu().numpy())
            all_targets.append(targets.cpu().numpy())
            all_outputs.append(outputs.cpu().numpy())
    
    inputs = np.concatenate(all_inputs, axis=0)
    targets = np.concatenate(all_targets, axis=0)
    outputs = np.concatenate(all_outputs, axis=0)
    
    # Calculate error (noise)
    error = outputs - targets
    
    # Calculate SNR and EVM for each example
    snrs = []
    evms_input = []
    evms_output = []
    
    for i in range(len(targets)):
        # SNR of output
        snr = calculate_snr(targets[i], error[i])
        snrs.append(snr)
        
        # EVM of input (noisy signal vs clean)
        evm_in = calculate_evm(inputs[i], targets[i])
        evms_input.append(evm_in)
        
        # EVM of output (denoised signal vs clean)
        evm_out = calculate_evm(outputs[i], targets[i])
        evms_output.append(evm_out)
    
    return np.array(snrs), np.array(evms_input), np.array(evms_output)


def train_model(model, train_loader, val_loader, device, epochs=50, lr=0.001):
    """Train the model and track performance."""
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', 
                                                       factor=0.5, patience=5)
    
    train_losses = []
    val_losses = []
    val_snrs = []
    
    best_val_loss = float('inf')
    
    for epoch in range(epochs):
        # Training
        model.train()
        train_loss = 0.0
        for inputs, targets in train_loader:
            inputs, targets = inputs.to(device), targets.to(device)
            
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item()
        
        train_loss /= len(train_loader)
        train_losses.append(train_loss)
        
        # Validation
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for inputs, targets in val_loader:
                inputs, targets = inputs.to(device), targets.to(device)
                outputs = model(inputs)
                loss = criterion(outputs, targets)
                val_loss += loss.item()
        
        val_loss /= len(val_loader)
        val_losses.append(val_loss)
        
        # Calculate SNR every 5 epochs
        if (epoch + 1) % 5 == 0:
            snrs, evms_in, evms_out = evaluate_snr(model, val_loader, device)
            mean_snr = np.mean(snrs)
            mean_evm_out = np.mean(evms_out)
            val_snrs.append(mean_snr)
            print(f"Epoch {epoch+1}/{epochs} - Train Loss: {train_loss:.6f}, "
                  f"Val Loss: {val_loss:.6f}, Val SNR: {mean_snr:.2f} dB, "
                  f"Val EVM: {mean_evm_out:.2f}%")
        else:
            print(f"Epoch {epoch+1}/{epochs} - Train Loss: {train_loss:.6f}, "
                  f"Val Loss: {val_loss:.6f}")
        
        scheduler.step(val_loss)
        
        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), 'best_model.pth')
    
    return train_losses, val_losses, val_snrs


def main():
    parser = argparse.ArgumentParser(description="Train 1D CNN for BPSK signal separation")
    parser.add_argument("--data", type=str, required=True, help="Path to .npz data file")
    parser.add_argument("--epochs", type=int, default=50, help="Number of training epochs")
    parser.add_argument("--batch_size", type=int, default=128, help="Batch size")
    parser.add_argument("--lr", type=float, default=0.001, help="Learning rate")
    args = parser.parse_args()
    
    # Load data
    print(f"Loading data from {args.data}...")
    data = np.load(args.data)
    Xtr, Ytr = data['Xtr'], data['Ytr']
    Xva, Yva = data['Xva'], data['Yva']
    
    print(f"Train set: {Xtr.shape}, Val set: {Xva.shape}")
    
    # Create datasets and dataloaders
    train_dataset = SignalDataset(Xtr, Ytr)
    val_dataset = SignalDataset(Xva, Yva)
    
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False)
    
    # Setup device
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")
    
    # Create model
    input_dim = Xtr.shape[1]  # Should be 512 (256 samples * 2)
    model = SignalDenoiser1DCNN(input_dim=input_dim).to(device)
    
    print(f"\nModel architecture:")
    print(model)
    print(f"\nTotal parameters: {sum(p.numel() for p in model.parameters()):,}")
    
    # Train
    print(f"\nStarting training for {args.epochs} epochs...")
    train_losses, val_losses, val_snrs = train_model(
        model, train_loader, val_loader, device, 
        epochs=args.epochs, lr=args.lr
    )
    
    # Load best model and evaluate final SNR
    model.load_state_dict(torch.load('best_model.pth'))
    final_snrs, final_evms_input, final_evms_output = evaluate_snr(model, val_loader, device)
    
    # Calculate EVM improvement
    evm_improvement = final_evms_input - final_evms_output
    
    print("\n" + "="*60)
    print("FINAL RESULTS")
    print("="*60)
    print(f"Mean Validation SNR: {np.mean(final_snrs):.2f} dB")
    print(f"Median Validation SNR: {np.median(final_snrs):.2f} dB")
    print(f"Std Validation SNR: {np.std(final_snrs):.2f} dB")
    print(f"Min/Max Validation SNR: {np.min(final_snrs):.2f} / {np.max(final_snrs):.2f} dB")
    print()
    print(f"Input EVM (before denoising): {np.mean(final_evms_input):.2f}% ± {np.std(final_evms_input):.2f}%")
    print(f"Output EVM (after denoising): {np.mean(final_evms_output):.2f}% ± {np.std(final_evms_output):.2f}%")
    print(f"EVM Improvement: {np.mean(evm_improvement):.2f}% ± {np.std(evm_improvement):.2f}%")
    print(f"EVM Reduction Factor: {np.mean(final_evms_input) / np.mean(final_evms_output):.2f}x")
    print()
    print(f"Best EVM achieved: {np.min(final_evms_output):.2f}%")
    print(f"Worst EVM achieved: {np.max(final_evms_output):.2f}%")
    
    # Plot results
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    
    # Loss curves
    axes[0, 0].plot(train_losses, label='Train Loss')
    axes[0, 0].plot(val_losses, label='Val Loss')
    axes[0, 0].set_xlabel('Epoch')
    axes[0, 0].set_ylabel('MSE Loss')
    axes[0, 0].set_title('Training and Validation Loss')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)
    
    # SNR over time
    if val_snrs:
        snr_epochs = np.arange(5, args.epochs + 1, 5)[:len(val_snrs)]
        axes[0, 1].plot(snr_epochs, val_snrs, marker='o', color='green')
        axes[0, 1].set_xlabel('Epoch')
        axes[0, 1].set_ylabel('SNR (dB)')
        axes[0, 1].set_title('Validation SNR During Training')
        axes[0, 1].grid(True, alpha=0.3)
    
    # SNR distribution
    axes[0, 2].hist(final_snrs, bins=50, edgecolor='black', alpha=0.7, color='green')
    axes[0, 2].axvline(np.mean(final_snrs), color='red', linestyle='--', 
                    label=f'Mean: {np.mean(final_snrs):.2f} dB')
    axes[0, 2].set_xlabel('SNR (dB)')
    axes[0, 2].set_ylabel('Count')
    axes[0, 2].set_title('Final SNR Distribution')
    axes[0, 2].legend()
    axes[0, 2].grid(True, alpha=0.3)
    
    # EVM comparison (Input vs Output)
    axes[1, 0].hist(final_evms_input, bins=50, alpha=0.5, label='Input EVM', 
                    edgecolor='black', color='red')
    axes[1, 0].hist(final_evms_output, bins=50, alpha=0.5, label='Output EVM', 
                    edgecolor='black', color='blue')
    axes[1, 0].set_xlabel('EVM (%)')
    axes[1, 0].set_ylabel('Count')
    axes[1, 0].set_title('EVM Distribution: Before vs After')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)
    
    # EVM improvement scatter
    axes[1, 1].scatter(final_evms_input, final_evms_output, alpha=0.3, s=10)
    max_evm = max(np.max(final_evms_input), np.max(final_evms_output))
    axes[1, 1].plot([0, max_evm], [0, max_evm], 'r--', label='No improvement')
    axes[1, 1].set_xlabel('Input EVM (%)')
    axes[1, 1].set_ylabel('Output EVM (%)')
    axes[1, 1].set_title('EVM: Input vs Output')
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)
    
    # EVM improvement distribution
    axes[1, 2].hist(evm_improvement, bins=50, edgecolor='black', alpha=0.7, color='purple')
    axes[1, 2].axvline(np.mean(evm_improvement), color='red', linestyle='--',
                       label=f'Mean: {np.mean(evm_improvement):.2f}%')
    axes[1, 2].set_xlabel('EVM Improvement (%)')
    axes[1, 2].set_ylabel('Count')
    axes[1, 2].set_title('EVM Improvement Distribution')
    axes[1, 2].legend()
    axes[1, 2].grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('training_results.png', dpi=150, bbox_inches='tight')
    print(f"\nPlots saved to training_results.png")
    print("="*60)


if __name__ == "__main__":
    main()